title: Vegan Developer
email: hallo@dionsnoeijen.nl
description: "Dion Snoeijen" #
baseurl: "" # 
url: "https://www.dionsnoeijen.nl"
twitter_username: dionsnoeijen
github_username: dionsnoeijen

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
sass:
 style: compressed
